language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

before_install:
  - python3 --version
  - uname -a
  - lsb_release -a
  - virtualenv --version
  - easy_install --version
  - pip --version
  # - tox --version

install:
  - pip install -U pip setuptools
  - pip install -r travis_requirements.txt

script:
    # - tox -v
    - py.test -l -vv --no-cov-on-fail --cov=docstats --cov-report=term-missing

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email:
    on_success: never
    on_failure: always
