#!/usr/bin/env python3
#
"""
Create visual statistics from GitHub repositories

Usage:
   docstats-vis [-h | --help]
   docstats-vis [-v...] [options] FILE

Options:
    -h, --help       Shows this help
    -v               Raise verbosity level
    --version        Prints the version
    FILE             The JSON result file which of the investigated Git repositories
"""

__version__ = "0.1.2"
__author__ = "Thomas Schraitle"


import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())

from docstats.log import log, setloglevel
import json


def parsecli(cliargs=None):
    from docopt import docopt
    version = "%s %s" % (__package__, __version__)
    args = docopt(__doc__, argv=cliargs, version=version)
    setloglevel(args['-v'])
    return args


def loadfile(filename):
    data = None
    with open(filename) as f:
        data = json.load(f)
    return data

if __name__ == "__main__":
    args = parsecli()
    log.info(args)
    filename = args['FILE']
    data = loadfile(filename)
    for key in sorted(data):
        print(key)
    print("Done")
